CREATE DATABASE cadastroresponsavel;
USE cadastroresponsavel;

CREATE TABLE responsavel (
	id INT AUTO_INCREMENT NOT NULL,
	nome VARCHAR(200) NOT NULL,
	dataNascimento VARCHAR(15) NOT NULL,
	telefone VARCHAR(20) NOT NULL,

	PRIMARY KEY(id)
);

CREATE TABLE aluno (
	prontuario VARCHAR(15) NOT NULL,
	idResponsavel INT NULL,
	senha VARCHAR(20) NOT NULL,
	dataNascimento VARCHAR(10) NOT NULL,
	telefone VARCHAR(20) NOT NULL,
	PRIMARY KEY(prontuario),
	FOREIGN KEY (idResponsavel) REFERENCES responsavel(id)
)
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
